version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 448049833640.dkr.ecr.eu-north-1.amazonaws.com

  build:
    commands:
      - echo Building Docker image...
      - docker build -t gsom-image .
      - docker tag gsom-image:latest 448049833640.dkr.ecr.eu-north-1.amazonaws.com/gsom-image:latest

  post_build:
    commands:
      - echo Pushing Docker image to Amazon ECR...
      - docker push 448049833640.dkr.ecr.eu-north-1.amazonaws.com/gsom-image:latest

      - echo Checking if SageMaker model exists...
      - |
        if aws sagemaker describe-model --model-name gsom-cloud-model --region eu-north-1; then
            echo "Model gsom-cloud-model already exists. Skipping model creation."
        else
            echo "Creating SageMaker Model..."
            aws sagemaker create-model --model-name gsom-cloud-model --primary-container Image=448049833640.dkr.ecr.eu-north-1.amazonaws.com/gsom-image:latest --execution-role-arn arn:aws:iam::448049833640:role/service-role/AmazonSageMaker-ExecutionRole --region eu-north-1
        fi

      - echo Creating SageMaker endpoint configuration...
      - |
        aws sagemaker create-endpoint-config --endpoint-config-name gsom-endpoint-config \
        --production-variants "[{\"VariantName\": \"gsom-variant-v1\", \"ModelName\": \"gsom-cloud-model\", \"InstanceType\": \"ml.c5.large\", \"InitialInstanceCount\": 1}]" --region eu-north-1 || echo "Endpoint config already exists, continuing..."

      - echo Checking if SageMaker endpoint exists and deleting it if present...
      - |
        if aws sagemaker describe-endpoint --endpoint-name gsom-cloud-endpoint --region eu-north-1; then
            echo "Deleting existing endpoint: gsom-cloud-endpoint..."
            aws sagemaker delete-endpoint --endpoint-name gsom-cloud-endpoint --region eu-north-1
        fi

      - echo Creating a new SageMaker endpoint...
      - aws sagemaker create-endpoint --endpoint-name gsom-cloud-endpoint --endpoint-config-name gsom-endpoint-config --region eu-north-1

artifacts:
  files:
    - '**/*'
